const actionTypes = {
  SET_FIELD: "SET_FIELD",
  SET_ERRORS: "SET_ERRORS",
  SET_IS_EDITING: "SET_IS_EDITING",
  SET_API_DATA: "SET_API_DATA",
  SET_SEARCH_TEXT: "SET_SEARCH_TEXT",
  SET_SELECTED_PRODUCTS: "SET_SELECTED_PRODUCTS",
  SET_DELETE_DIALOG_VISIBLE: "SET_DELETE_DIALOG_VISIBLE",
  SET_DELETE_TARGET: "SET_DELETE_TARGET",
  SET_DELETE_SELECTED_DIALOG_VISIBLE: "SET_DELETE_SELECTED_DIALOG_VISIBLE",
};
export default actionTypes;
